Repository codingo/Interlace, pull requests merged in 2019-08, with the labels that each got.

#57 Permissions bug fix
  Interlace/lib/core/__version__.py
  Interlace/lib/core/input.py
Labels: bug

#61 Fix arguments.output bug introduced in #57
  Interlace/lib/core/input.py
Labels: bug

#58 Introduce _random_ feature as per #50
  Interlace/lib/core/input.py
  README.md
Labels: enhancement

#62 Escape _random_ in README.md
  README.md
Labels: bug

#60 Add _block:_ and _blocker_ features as per #52 (flat implementation)
  .github/FUNDING.yml
  Interlace/interlace.py
  Interlace/lib/core/input.py
  Interlace/lib/core/output.py
  Interlace/lib/threader.py
  bar.test
  foo.test
  setup.py
Labels: enhancement

#69 Patch for Attribute Error
  Interlace/lib/core/input.py
Labels: bug

#71 Added support for anonymous block
  Interlace/lib/core/input.py
Labels: bug, enhancement

#74 Add label workflow
  .github/workflows/label.yml
Labels: enhancement
